package com.mycompany.sistemagestioncine.views;

public class MDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MDI.class.getName());

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }
    
    public void mostrarVistaCentral(javax.swing.JPanel vista) {
    vista.setSize(panelCentral.getWidth(), panelCentral.getHeight());
    vista.setLocation(0, 0);
    
    panelCentral.removeAll();
    panelCentral.add(vista, java.awt.BorderLayout.CENTER);
    
    panelCentral.revalidate();
    panelCentral.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenuPeliculas = new javax.swing.JButton();
        btnMenuSalas = new javax.swing.JButton();
        btnVenderTickets = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnMenuCartelera = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenuPeliculas.setText("Peliculas");
        btnMenuPeliculas.addActionListener(this::btnMenuPeliculasActionPerformed);

        btnMenuSalas.setText("Salas");
        btnMenuSalas.addActionListener(this::btnMenuSalasActionPerformed);

        btnVenderTickets.setText("Venta Tickets");
        btnVenderTickets.addActionListener(this::btnVenderTicketsActionPerformed);

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        btnMenuCartelera.setText("Cartelera");
        btnMenuCartelera.addActionListener(this::btnMenuCarteleraActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenderTickets)
                    .addComponent(btnCerrarSesion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMenuPeliculas)
                            .addComponent(btnMenuSalas)
                            .addComponent(btnMenuCartelera))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnMenuPeliculas)
                .addGap(78, 78, 78)
                .addComponent(btnMenuCartelera)
                .addGap(95, 95, 95)
                .addComponent(btnMenuSalas)
                .addGap(60, 60, 60)
                .addComponent(btnVenderTickets)
                .addGap(60, 60, 60)
                .addComponent(btnCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuSalasActionPerformed
        // TODO add your handling code here:
        SalasView vistaSalas = new SalasView();
        mostrarVistaCentral(vistaSalas);
    }//GEN-LAST:event_btnMenuSalasActionPerformed

    private void btnMenuPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPeliculasActionPerformed
        // TODO add your handling code here:
        PeliculasView vistaPeliculas = new PeliculasView();
        mostrarVistaCentral(vistaPeliculas);
    }//GEN-LAST:event_btnMenuPeliculasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro que deseas cerrar sesión?", 
            "Cerrar Sesión", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            this.dispose(); 

            Login loginView = new Login();
            loginView.setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnVenderTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderTicketsActionPerformed
        // TODO add your handling code here:
            javax.swing.JOptionPane.showMessageDialog(this, 
            "Módulo de Ventas en construcción...", 
            "Aviso", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVenderTicketsActionPerformed

    private void btnMenuCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCarteleraActionPerformed
        CarteleraVieww carteleraSalass = new CarteleraVieww();
        mostrarVistaCentral(carteleraSalass);
    }//GEN-LAST:event_btnMenuCarteleraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMenuCartelera;
    private javax.swing.JButton btnMenuPeliculas;
    private javax.swing.JButton btnMenuSalas;
    private javax.swing.JButton btnVenderTickets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables

    private void mostrarVistaCentral() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
}
