package views;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JToggleButton;

public class MapaAsientosView extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MapaAsientosView.class.getName());

    /**
     * Creates new form MapaAsientosView
     */
    public MapaAsientosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarControles();
    }
    
    private final java.util.Map<Integer, JToggleButton> botones = new java.util.LinkedHashMap<>();
    private final javax.swing.JButton confirmar = new javax.swing.JButton("Confirmar compra");
    private int cantidadRequerida;

    private void configurarControles() {
        setLayout(new java.awt.BorderLayout(8, 8));
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(panelCuadricula);
        scroll.setPreferredSize(new java.awt.Dimension(640, 415));
        add(scroll, java.awt.BorderLayout.CENTER);
        javax.swing.JPanel acciones = new javax.swing.JPanel();
        javax.swing.JButton cancelar = new javax.swing.JButton("Cancelar");
        cancelar.addActionListener(e -> dispose());
        acciones.add(confirmar); acciones.add(cancelar);
        add(acciones, java.awt.BorderLayout.SOUTH);
        confirmar.setEnabled(false);
        pack();
        setLocationRelativeTo(getOwner());
    }

    public void mostrarAsientos(java.util.List<models.Asiento> asientos, java.util.Set<Integer> vendidos, int cantidad) {
        cantidadRequerida = cantidad;
        botones.clear(); panelCuadricula.removeAll();
        panelCuadricula.setLayout(new java.awt.GridBagLayout());
        java.util.Map<String, Integer> filas = new java.util.LinkedHashMap<>();
        for (models.Asiento asiento : asientos) {
            int fila = filas.computeIfAbsent(asiento.getFila(), key -> filas.size());
            JToggleButton boton = new JToggleButton(asiento.getFila() + "-" + asiento.getNumero());
            boton.setToolTipText(asiento.getTipoDeAsiento() + " · " + asiento.getEstado());
            boolean vendido = vendidos.contains(asiento.getIdAsiento());
            boolean disponible = "Disponible".equals(asiento.getEstado()) && !vendido;
            boton.setEnabled(disponible);
            boton.setBackground(vendido ? Color.RED : disponible ? Color.GREEN : Color.GRAY);
            boton.addActionListener(e -> {
                if (getAsientosSeleccionados().size() > cantidadRequerida) {
                    boton.setSelected(false);
                    utils.Tareas.error(this, "Solo puedes seleccionar " + cantidadRequerida + " asientos.");
                }
                boton.setBackground(boton.isSelected() ? Color.RED : Color.GREEN);
                confirmar.setEnabled(getAsientosSeleccionados().size() == cantidadRequerida);
            });
            java.awt.GridBagConstraints celda = new java.awt.GridBagConstraints();
            celda.gridx = asiento.getNumero() - 1; celda.gridy = fila;
            celda.insets = new java.awt.Insets(3, 3, 3, 3); celda.fill = java.awt.GridBagConstraints.HORIZONTAL;
            panelCuadricula.add(boton, celda); botones.put(asiento.getIdAsiento(), boton);
        }
        confirmar.setEnabled(false);
        panelCuadricula.revalidate(); panelCuadricula.repaint();
    }

    public java.util.List<Integer> getAsientosSeleccionados() {
        return botones.entrySet().stream().filter(e -> e.getValue().isSelected())
                .map(java.util.Map.Entry::getKey).toList();
    }

    public void addConfirmarListener(java.awt.event.ActionListener listener) { confirmar.addActionListener(listener); }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuadricula = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCuadricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelCuadriculaLayout = new javax.swing.GroupLayout(panelCuadricula);
        panelCuadricula.setLayout(panelCuadriculaLayout);
        panelCuadriculaLayout.setHorizontalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        panelCuadriculaLayout.setVerticalGroup(
            panelCuadriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuadricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MapaAsientosView dialog = new MapaAsientosView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCuadricula;
    // End of variables declaration//GEN-END:variables
}
