package views;

import views.estilos.Tema;

public class SalasView extends javax.swing.JPanel {

    /**
     * Creates new form SalasView
     */
    public SalasView() {
        initComponents();
        aplicarEstilos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAsientosFila = new javax.swing.JTextField();
        txtTiempoLimpieza = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        txtAsientosEspeciales = new javax.swing.JTextField();
        btnNuevaSala = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalas = new javax.swing.JTable();
        pnlCabecera = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 245, 247));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 101, 121));
        jLabel1.setText("Capacidad Total:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 101, 121));
        jLabel2.setText("Asientos Especiales:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 101, 121));
        jLabel3.setText("Tiempo Limpieza(min):");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 101, 121));
        jLabel4.setText("Asientos por Fila:");

        txtAsientosFila.addActionListener(this::txtAsientosFilaActionPerformed);

        txtTiempoLimpieza.addActionListener(this::txtTiempoLimpiezaActionPerformed);

        txtCapacidad.addActionListener(this::txtCapacidadActionPerformed);

        txtAsientosEspeciales.addActionListener(this::txtAsientosEspecialesActionPerformed);

        btnNuevaSala.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNuevaSala.setText("Nueva Sala");
        btnNuevaSala.addActionListener(this::btnNuevaSalaActionPerformed);

        btnGuardarCambios.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnGuardarCambios.setText("Guardar Cambios");

        tblSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Capacidad Total", "Asientos Especiales", "Tiempo de Limpieza (min)", "Asientos por Fila"
            }
        ));
        jScrollPane1.setViewportView(tblSalas);

        pnlCabecera.setBackground(new java.awt.Color(24, 34, 53));
        pnlCabecera.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 20, 24));
        pnlCabecera.setLayout(new javax.swing.BoxLayout(pnlCabecera, javax.swing.BoxLayout.PAGE_AXIS));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gestión de Salas");
        pnlCabecera.add(lblTitulo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAsientosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAsientosFila, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTiempoLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(pnlCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaSala)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsientosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnGuardarCambios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsientosFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTable getTablaSalas() { 
        return tblSalas; 
    }
    
    public void addNuevaListener(java.awt.event.ActionListener listener) { 
        btnNuevaSala.addActionListener(listener); 
    }
    
    public void addGuardarListener(java.awt.event.ActionListener listener) { 
        btnGuardarCambios.addActionListener(listener); 
    }

    public models.Sala leerSala() {
        return new models.Sala(
                Integer.parseInt(txtCapacidad.getText().trim()),
                txtAsientosEspeciales.getText().trim().isEmpty() ? 0 : Integer.parseInt(txtAsientosEspeciales.getText().trim()),
                Integer.parseInt(txtTiempoLimpieza.getText().trim()), 
                Integer.parseInt(txtAsientosFila.getText().trim()), 
                "ACTIVA"
        );
    }

    public void mostrarSala(models.Sala sala) {
        txtCapacidad.setText(Integer.toString(sala.getCapacidadTotal()));
        txtAsientosEspeciales.setText(Integer.toString(sala.getAsientosEspeciales()));
        txtTiempoLimpieza.setText(Integer.toString(sala.getTiempoDeLimpieza()));
        txtAsientosFila.setText(Integer.toString(sala.getAsientosPorFila()));
    }

    public void limpiarFormulario() {
        txtCapacidad.setText(""); 
        txtAsientosEspeciales.setText("0");
        txtTiempoLimpieza.setText(""); 
        txtAsientosFila.setText("");
    }
    
    private void aplicarEstilos() {
        this.setBackground(java.awt.Color.WHITE); 

        btnGuardarCambios.setBackground(Tema.PRIMARIO);
        btnGuardarCambios.setForeground(java.awt.Color.WHITE);
        btnGuardarCambios.setFont(Tema.CUERPO.deriveFont(java.awt.Font.BOLD));
        btnGuardarCambios.setFocusPainted(false); 
        btnGuardarCambios.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 24, 10, 24)); 
        btnGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnNuevaSala.setBackground(Tema.SECUNDARIO);
        btnNuevaSala.setForeground(java.awt.Color.WHITE);
        btnNuevaSala.setFont(Tema.CUERPO.deriveFont(java.awt.Font.BOLD));
        btnNuevaSala.setFocusPainted(false);
        btnNuevaSala.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 24, 10, 24));
        btnNuevaSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.JTextField[] campos = {txtCapacidad, txtAsientosEspeciales, txtTiempoLimpieza, txtAsientosFila};
        for (javax.swing.JTextField campo : campos) {
            campo.setFont(Tema.CUERPO);
            campo.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 225, 232)), 
                javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
            ));
        }
        
        lblTitulo.setFont(Tema.TITULO);
        lblTitulo.setForeground(Tema.TEXTO);
        pnlCabecera.setBackground(Tema.TEXTO); // Azul oscuro
        lblTitulo.setForeground(java.awt.Color.WHITE); // Texto blanco
        lblTitulo.setFont(Tema.TITULO);

        jLabel1.setFont(Tema.ETIQUETA);
        jLabel1.setForeground(Tema.TEXTO);
        jLabel2.setFont(Tema.ETIQUETA);
        jLabel2.setForeground(Tema.TEXTO);
        jLabel3.setFont(Tema.ETIQUETA);
        jLabel3.setForeground(Tema.TEXTO);
        jLabel4.setFont(Tema.ETIQUETA);
        jLabel4.setForeground(Tema.TEXTO);

        tblSalas.setFont(Tema.CUERPO);
        tblSalas.getTableHeader().setFont(Tema.ETIQUETA);
        tblSalas.getTableHeader().setBackground(Tema.TEXTO);
        tblSalas.getTableHeader().setForeground(java.awt.Color.WHITE);
        tblSalas.setRowHeight(44); 
        tblSalas.setShowGrid(false); 
        tblSalas.setIntercellSpacing(new java.awt.Dimension(0, 0));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 225, 232)));
    }

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            javax.swing.JFrame ventana = new javax.swing.JFrame("Prueba aislada - Gestión de Salas");
            ventana.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            ventana.setContentPane(new SalasView());
            ventana.setSize(800, 500);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
        });
    }
    
    private void txtAsientosFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsientosFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsientosFilaActionPerformed

    private void txtTiempoLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoLimpiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoLimpiezaActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void txtAsientosEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsientosEspecialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsientosEspecialesActionPerformed

    private void btnNuevaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnNuevaSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JTable tblSalas;
    private javax.swing.JTextField txtAsientosEspeciales;
    private javax.swing.JTextField txtAsientosFila;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtTiempoLimpieza;
    // End of variables declaration//GEN-END:variables
}
