package views;

public class SalasView extends javax.swing.JPanel {

    /**
     * Creates new form Salas
     */
    public SalasView() {
        initComponents();
    }

    public javax.swing.JTable getTablaSalas() { return tblSalas; }
    public void addNuevaListener(java.awt.event.ActionListener listener) { btnNuevaSala.addActionListener(listener); }
    public void addGuardarListener(java.awt.event.ActionListener listener) { btnGuardarCambios.addActionListener(listener); }

    public models.Sala leerSala() {
        return new models.Sala(Integer.parseInt(txtCapacidad.getText().trim()),
                txtAsientosEspeciales.getText().isBlank() ? 0 : Integer.parseInt(txtAsientosEspeciales.getText().trim()),
                Integer.parseInt(txtTiempoLimpieza.getText().trim()), Integer.parseInt(txtAsientosFila.getText().trim()), "ACTIVA");
    }

    public void mostrarSala(models.Sala sala) {
        txtCapacidad.setText(Integer.toString(sala.getCapacidadTotal()));
        txtAsientosEspeciales.setText(Integer.toString(sala.getAsientosEspeciales()));
        txtTiempoLimpieza.setText(Integer.toString(sala.getTiempoDeLimpieza()));
        txtAsientosFila.setText(Integer.toString(sala.getAsientosPorFila()));
    }

    public void limpiarFormulario() {
        txtCapacidad.setText(""); txtAsientosEspeciales.setText("0");
        txtTiempoLimpieza.setText(""); txtAsientosFila.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        txtAsientosEspeciales = new javax.swing.JTextField();
        txtTiempoLimpieza = new javax.swing.JTextField();
        txtAsientosFila = new javax.swing.JTextField();
        btnNuevaSala = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalas = new javax.swing.JTable();

        jLabel1.setText("Capacidad Total:");

        jLabel2.setText("Asientos Especiales:");

        jLabel3.setText("Tiempo Limpieza(min):");

        jLabel4.setText("Asientos por Fila:");

        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });

        txtAsientosEspeciales.addActionListener(this::txtAsientosEspecialesActionPerformed);
        txtAsientosEspeciales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAsientosEspecialesKeyTyped(evt);
            }
        });

        txtTiempoLimpieza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiempoLimpiezaKeyTyped(evt);
            }
        });

        txtAsientosFila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAsientosFilaKeyTyped(evt);
            }
        });

        btnNuevaSala.setText("Nueva Sala");
        btnNuevaSala.addActionListener(this::btnNuevaSalaActionPerformed);

        btnGuardarCambios.setText("Guardar Cambios");

        tblSalas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Capacidad Total", "Asientos Especiales", "Tiempo de Limpieza (min)", "Asientos por Fila"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSalas);
        if (tblSalas.getColumnModel().getColumnCount() > 0) {
            tblSalas.getColumnModel().getColumn(0).setResizable(false);
            tblSalas.getColumnModel().getColumn(1).setResizable(false);
            tblSalas.getColumnModel().getColumn(2).setResizable(false);
            tblSalas.getColumnModel().getColumn(3).setResizable(false);
        }

        // CORRECCIÓN APLICADA AQUÍ: Se eliminó getContentPane() y se reemplazó por 'this'
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTiempoLimpieza)
                            .addComponent(txtAsientosEspeciales)
                            .addComponent(txtAsientosFila))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNuevaSala)
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardarCambios)
                                .addGap(44, 44, 44))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAsientosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiempoLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAsientosFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnNuevaSala)
                        .addGap(48, 48, 48)
                        .addComponent(btnGuardarCambios)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        // CORRECCIÓN APLICADA AQUÍ: Se eliminó la instrucción pack();
    }// </editor-fold>                          

    private void txtAsientosEspecialesActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void btnNuevaSalaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Si el carácter presionado NO es un dígito (0-9), bloqueamos la tecla
        if (!Character.isDigit(c)) {
            evt.consume(); 
        // Opcional: puedes hacer un sonido de error con java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }                                     

    private void txtAsientosEspecialesKeyTyped(java.awt.event.KeyEvent evt) {                                               
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        // Si el carácter presionado NO es un dígito (0-9), bloqueamos la tecla
        if (!Character.isDigit(c)) {
            evt.consume(); 
        // Opcional: puedes hacer un sonido de error con java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }                                              

    private void txtTiempoLimpiezaKeyTyped(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        // Si el carácter presionado NO es un dígito (0-9), bloqueamos la tecla
        if (!Character.isDigit(c)) {
            evt.consume(); 
        // Opcional: puedes hacer un sonido de error con java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }                                          

    private void txtAsientosFilaKeyTyped(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        // Si el carácter presionado NO es un dígito (0-9), bloqueamos la tecla
        if (!Character.isDigit(c)) {
            evt.consume(); 
        // Opcional: puedes hacer un sonido de error con java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }                                        

    public boolean isFormularioValido() {
    // Verificamos si algún campo está vacío (quitando los espacios en blanco con trim)
    if (txtCapacidad.getText().trim().isEmpty() || 
        txtTiempoLimpieza.getText().trim().isEmpty() || 
        txtAsientosFila.getText().trim().isEmpty()) {

        // Mostramos el mensaje de error
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, completa todos los campos requeridos.", 
            "Error de Validación", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return false; // Retorna falso porque el formulario tiene errores
    }
    return true; // Retorna verdadero si todo está lleno
}

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnNuevaSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalas;
    private javax.swing.JTextField txtAsientosEspeciales;
    private javax.swing.JTextField txtAsientosFila;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtTiempoLimpieza;
    // End of variables declaration                   
}
